/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_EmulatorHandler */

#ifndef _Included_com_turbosanta_EmulatorHandler
#define _Included_com_turbosanta_EmulatorHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_EmulatorHandler
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_EmulatorHandler_init
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_turbosanta_EmulatorHandler
 * Method:    launch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_EmulatorHandler_launch
  (JNIEnv *, jclass);

/*
 * Class:     com_turbosanta_EmulatorHandler
 * Method:    handleInput
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_EmulatorHandler_handleInput
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
